/* This file is automatically generated by staticizer.py*/

const LV2_Descriptor *lv2_descriptor_piano(uint32_t index);
const LV2_Descriptor *lv2_descriptor_organ(uint32_t index);

const void* lv2_descriptor_loaders[] = {
    lv2_descriptor_piano,
    lv2_descriptor_organ,
    NULL
};

